version: '3.9'
services:
  app1:
    build:
      context: .
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"

  app2:
    build:
      context: .
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"

  app3:
    build:
      context: .
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"

  # server:
  #   build:
  #     context: .
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000